services:
  - type: web
    name: my-email-tracker
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app
    pythonVersion: 3.12.3
